### ISSUE TITLE
Fix : Back key(Android?)

### ISSUE THREAD

**Issue by kwish2** [wafflestudio/guam-community-mobile#147]
**Describe the bug**
홈 탭을 제외한 검색, 프로필 탭에서 게시글 상세 페이지 이동 후 안드로이드 뒤로가기 버튼을 누르면 이전 페이지로 이동하지 않고 앱이 종료됨. (프로필 -> 스크랩한 글, 프로필 -> 내가 쓴 글 목록에서도 마찬가지로 앱 종료됨)

**Expected behavior**
뒤로가기 버튼을 누르면 앱이 종료되는 것이 아닌 이전 페이지로 되돌아가도록 수정할 필요가 있어 보임.

**Comment by YeonghyeonKO** [comment]
[lib/screens/profiles/profile/profile_bottom_buttons.dart](https://github.com/wafflestudio/guam-community-mobile/blob/e6875665159beae69ea2150e9037d57501f05059/lib/screens/profiles/profile/profile_bottom_buttons.dart)에서 Navigator.push로 MaterialPageRoute 가게 하는데도 그렇군요. 제가 Xcode 위주로 build 중이라 이따 집가서 안드 살펴보겠습니다
