### ISSUE TITLE
Fix/검색 탭 UI 일부 변경

### ISSUE THREAD

**Issue by YeonghyeonKO** [wafflestudio/guam-community-mobile#40]
- [ ] 검색창 우측에 검색어를 삭제할 수 있는 (x) 버튼 신설 (현재는 `취소` 버튼이 해당 기능을 수행 중)

- [ ] `취소` 버튼을 눌렀을 때는 최근 검색어를 볼 수 있는 기본 페이지로 이동

**Comment by YeonghyeonKO** [comment]
@gajagajago 준열님 현재 **히스토리** 컨테이너와 **검색 결과** 컨테이너가 사실상 같은 페이지인데요, 
1) 페이지를 나누어 각각 **(x)** 버튼과 **취소** 버튼의 로직을 다르게 설정할지(그렇다면 검색 결과 페이지에서 **취소**를 누르면 `Navigator.pop();` 정도로 구현됩니다.)

2) 현재 방식대로 하나의 페이지로 놔두되, 여러 boolean(`showHistory`, `isTextEmpty` 등)을 설정하여 케이스별로 **(x)**와 **취소** 버튼이 보일지 말지, 해당 버튼을 누르면 어떤 기능을 수행할 것인지

위 두 방식에 대해 고민중입니다.

**Comment by gajagajago** [comment]
네 확인했습니다. 개인적으로 2를 선호하지만, 관련 사항 간단히 스크럼에서 얘기해보면 좋을 것 같습니다.

**Comment by YeonghyeonKO** [comment]
@gajagajago 넵! 일단 2로 구현하려고 하고는 있는데, 케이스가 워낙 많아 boolean끼리 &&랑 ||로 겹치고 난리나더라구요 ㅋㅋㅋ 풀 받으셔서 체크해보셔도 됩니다 (미완이지만)
