### ISSUE TITLE
isKakaoInstalled possible issue 

### ISSUE THREAD

**Issue by gajagajago** [wafflestudio/guam-community-mobile#45]
<img width="694" alt="스크린샷 2022-02-09 오후 12 21 22" src="https://user-images.githubusercontent.com/52441827/153115727-75131dc0-e54d-4e1e-b1c5-4ac703e24d62.png">

**Comment by YeonghyeonKO** [comment]
아래 링크가 관련된 문서인가보군요 
- https://github.com/kakao/kakao_flutter_sdk#getting-authorization-code
- https://developers.kakao.com/docs/latest/ko/getting-started/sdk-ios-v1#app-key
